### ISSUE TITLE
Zeal ist started twice

### ISSUE THREAD

**Issue by fkjogu** [blakeembrey/atom-dash#33] opened 2016-04-15 12:40 UTC
When executing *dash:shortcut* Zeal is started twice, but only once when it is already open. For some reason the *shortcut* function is called twice. But I'm too unfamiliar with Atom to understand the reason for that.

Is there a mechanism that retries to start Dash/Zeal again, if the first call failed?

Using Atom 1.7.0 and atom-dash 1.6.0 on Debian 8 Linux.

**Comment by blakeembrey** [comment] 2016-04-15 16:20
> Is there a mechanism that retries to start Dash/Zeal again, if the first call failed?

No, there's is not. The code is fairly simple. I'd ask the Zeal team, perhaps?

**Comment by trollixx** [comment] 2016-04-17 01:34
I've managed to reproduce the scenario in my synthetic tests. I think this ticket can be closed. Please follow zealdocs/zeal#535.

**Comment by trollixx** [comment] 2016-04-17 01:48
On thought thought it could be not Zeal's fault. At least not entirely. Something should still launch Zeal twice in a literally no time.

@fkjogu is it possible that <kbd>Ctrl-H</kbd> gets pressed more than one time? Also, what's your desktop environment?

**Comment by fkjogu** [comment] 2016-04-20 13:53
Funny, at the moment I'm not able to reproduce this myself anymore. Probably some racing condition.

**Comment by blakeembrey** [comment] 2016-04-20 18:03
@fkjogu I'll close this for now then. Feel free to re-open if it persists, but it was properly caused by Atom - I'm not sure how the plugin itself could have triggered double.

**Closed by blakeembrey** 2016-04-20 18:03 UTC
